### PR TITLE
Fix UTM, LCC, Krovak and Stere projections

### LINKED ISSUE #25: Invalid conversion EPSG:5514 - JTSK
I get wrong result for EPSG:5514 - JTSK specified by proj4j parameters. Conversion WGS84 -> JTSK is almost correct except SIGNs. Conversion from JTSK -> WGS84 is WRONG.

JTSK : ProjCoordinate[747963.6497538437 1041493.3287851878 NaN]  // negative signs
WGS84: ProjCoordinate[24.834517978270924 -59.948074516468246 NaN] // - wrong should be: 14.346996204306555,50.09465901453681

Values and code example is derived from JavaScript:
http://jsfiddle.net/xiceph/79QHW/1/

https://github.com/proj4js/proj4js/issues/115

```
    private static final CoordinateTransformFactory ctFactory = new CoordinateTransformFactory();
    private static final String JTSK_PARAM_5514 = "+title=Krovak +proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +units=m +towgs84=570.8,85.7,462.8,4.998,1.587,5.261,3.56 +no_defs";
    private static final CoordinateReferenceSystem WGS84 = new CRSFactory().createFromName("epsg:4326");
    private static final CoordinateReferenceSystem JTSK_5514 = new CRSFactory().createFromParameters("JTSK", JTSK_PARAM_5514);

    public static void main(final String[] args) {
        CoordinateTransform transFromWGS84 = ctFactory.createTransform(WGS84, JTSK_5514);
        CoordinateTransform transToWGS84 = ctFactory.createTransform(JTSK_5514, WGS84);
        ProjCoordinate pout = new ProjCoordinate();
        ProjCoordinate srcWGS84 = new ProjCoordinate( 14.346996204306555,50.09465901453681);
        System.out.println("JTSK : " + transFromWGS84.transform(srcWGS84, pout));
        pout = new ProjCoordinate( -747963.64999999851, -1041493.3299999982);
        System.out.println("WGS84: " + transToWGS84.transform(pout, new ProjCoordinate()));
}
```

### LINKED ISSUE #58: *2 in stereographic projection near the equator
When I set the base point for stereographic projection on the equator, an unexpected *2 appears in the results compared to the case when the base point is only near the equator.

Example code:

```
CRSFactory csFactory = new CRSFactory();
CoordinateReferenceSystem STERE0 = csFactory.createFromParameters("STERE", "+proj=stere +lat_0=0.0 +lon_0=0.0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs");
CoordinateReferenceSystem STERE1 = csFactory.createFromParameters("STERE", "+proj=stere +lat_0=0.000001 +lon_0=0.0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs");
CoordinateReferenceSystem WGS84 = csFactory.createFromParameters("WGS84", "+proj=latlong +datum=WGS84 +ellps=WGS84 +no_defs");
CoordinateTransform transformer0 = new CoordinateTransformFactory().createTransform(WGS84, STERE0);
CoordinateTransform transformer1 = new CoordinateTransformFactory().createTransform(WGS84, STERE1);
        
ProjCoordinate pc = new ProjCoordinate(1, 1);
ProjCoordinate result0 = new ProjCoordinate();
ProjCoordinate result1 = new ProjCoordinate();

transformer0.transform(pc, result0);
transformer1.transform(pc, result1);
System.out.println(result0.x + ", " + result0.y);
System.out.println(result1.x + ", " + result1.y);
```

And the result is:

`222627.90213684924, 221171.23231657242`
`111313.95105169504, 110585.50558411982`

I'm not good at projections, but it seems weird for me. In the file
https://github.com/locationtech/proj4j/blob/master/src/main/java/org/locationtech/proj4j/proj/StereographicAzimuthalProjection.java
I can see from line 146:
```
			case OBLIQUE:
				A = akm1 / (cosphi0 * (1. + sinphi0 * sinX + cosphi0 * cosX * coslam));
				xy.y = A * (cosphi0 * sinX - sinphi0 * cosX * coslam);
				xy.x = A * cosX;
				break;
			case EQUATOR:
				A = 2. * akm1 / (1. + cosX * coslam);
				xy.y = A * sinX;
				xy.x = A * cosX;
				break;
```
What is that 2* there, and why is it necessary?

(I use version 1.1.0 from maven.)

### LINKED ISSUE #61: WebMercator EPSG code retrieved from proj4 parameters returns a legacy value
The EPSG code of WebMercator projection created from the proj4 string returns a legacy value;
`EPSG:3785` instead of `EPSG:3857`; to reproduce the behavior use the following code:

```java
crsFactory
  .readEpsgFromParameters("+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs")
```

### PR DESCRIPTION
**Pull request by pomadchin**
## Summary

- Fix UTM projection (it is backed by etmerc now, made tests much better (!))
- Fix tests 
- Resurrect proj4-epsg tests and update them up to date

### Test resurrection results
Before this PR [proj4-epsg.csv](https://github.com/locationtech/proj4j/blob/v1.1.1/src/test/resources/proj4-epsg.csv) contained the following amount of tests: 
- passing: 2899
- failing: 1089
- error: 292

After:
- passing: 3941 (893 tests were fixed due to the `ExtendedTransverseMercatorProjection`)
- failing: 195
- error: 144 (geocent projection is supported now)

**UPD**

After (with LCC projection fix):
- passing: 4098
- failing: 38
- error: 144
 
 **UPD2**

After (with Krovak projection fix):
- passing: 4104
- failing: 34
- error: 144

Closes #25
Closes #58
Closes #61

### CODE REVIEW

File: src/main/java/org/locationtech/proj4j/Registry.java [hunk 1]
```diff
@@ -266,32 +263,30 @@ private synchronized void initialize() {
...
-//    register( "tpers", Projection.class, "Tilted perspective" );
-//    register( "ups", Projection.class, "Universal Polar Stereographic" );
-//    register( "urm5", Projection.class, "Urmaev V" );
+        // register( "tpeqd", Projection.class, "Two Point Equidistant" );
+        // register( "tpers", Projection.class, "Tilted perspective" );
+        // register( "ups", Projection.class, "Universal Polar Stereographic" );
+        // register( "urm5", Projection.class, "Urmaev V" );
         register("urmfps", UrmaevFlatPolarSinusoidalProjection.class, "Urmaev Flat-Polar Sinusoidal");
-        register("utm", TransverseMercatorProjection.class, "Universal Transverse Mercator (UTM)");
+        register("utm", ExtendedTransverseMercatorProjection.class, "Universal Transverse Mercator (UTM)");
```
Comment (pomadchin) [inline src/main/java/org/locationtech/proj4j/Registry.java:274]: That's the UTM projection fix itself.

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Fixed
 
 - Fix NZ Map projection and add a test for it [#62](https://github.com/locationtech/proj4j/issues/62)
+- Fix UTM projection [#71](https://github.com/locationtech/proj4j/pull/71)
+- Update OrthographicAzimuthalProjection [#63](https://github.com/locationtech/proj4j/pull/63)
```
Comment (pomadchin) [inline CHANGELOG.md:13]: Changelog update to reflect recently merged enhancements.

**Review by echeipesh — APPROVED** [review]
LGTM, tests done lie.
Note: added test cases came from Proj4JS
